
sudo: required


language: node_js
node_js:
  - "8"

branches:
  only:
    - develop

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

# use chromium instead of chrome
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
  - ng test --watch=false
